apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helm-generic-chart
  namespace: team-a
spec:
  interval: 1m0s
  provider: github
  secretRef:
    name: flux-system
  url: https://github.com/git-ops92/helm-generic-chart
  ref:
    name: refs/heads/main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/chart/